### ISSUE TITLE
Hardcoded URI

### ISSUE THREAD

**Issue by IgnoredAmbience** [resource-reasoning/testing-website#2]
https://github.com/resource-reasoning/testing-website/blob/migration/testing/templates/create_group.pt#L59

Should be using the method provided by pyramid to generate a URI to that controller -- otherwise breaks the prefix remapping.

**Comment by Archosian** [comment]
[Fixed cb6274](https://github.com/resource-reasoning/testing-website/commit/cb6274568da40846e2904651e2e7488459eadaf9)
